# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowApplicationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_open', models.BooleanField(default=False)),
                ('apply_page_subtitle', models.TextField(blank=True, verbose_name='Application Page Subtitle')),
            ],
            options={
                'verbose_name': 'Show Applications Settings',
            },
        ),
    ]
