# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_showapplicationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='showapplication',
            name='biweekly',
            field=models.BooleanField(default=False, verbose_name='Bi-weekly show?'),
        ),
        migrations.AddField(
            model_name='showapplication',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Host Contact Phone'),
        ),
        migrations.AddField(
            model_name='showapplication',
            name='host_name',
            field=models.CharField(blank=True, max_length=80, verbose_name="Host's Name"),
        ),
        migrations.AddField(
            model_name='showapplication',
            name='new_show',
            field=models.BooleanField(default=False, verbose_name='New show?'),
        ),
        migrations.AddField(
            model_name='showapplication',
            name='producer_name',
            field=models.CharField(blank=True, max_length=80, verbose_name="Producer's Name"),
        ),
        migrations.AlterField(
            model_name='showapplication',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Host Contact Email'),
        ),
    ]
