# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-23 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_timeslotrequest_biweekly_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotrequest',
            name='biweekly_partner',
            field=models.OneToOneField(blank=True, help_text='The show that runs biweekly with the first show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biweekly_slot', to='applications.ShowApplication', verbose_name='Even-week show'),
        ),
    ]
