# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-28 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('podcast_id', models.IntegerField(verbose_name='Podcast ID')),
                ('playlist_id', models.IntegerField(verbose_name='Playlist ID')),
                ('is_public', models.BooleanField(verbose_name='visibility')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('sharpstream_v1', 'Sharpstream RSS API')], max_length=60, verbose_name='Podcasts Provider')),
                ('api_key', models.CharField(max_length=200)),
                ('client_id', models.IntegerField(verbose_name='Client ID')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcasts.PodcastProvider'),
        ),
    ]
