# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Spotify show ID'),
        ),
        migrations.AlterField(
            model_name='podcastprovider',
            name='type',
            field=models.CharField(choices=[('sharpstream_v1', 'Sharpstream RSS API'), ('spotify', 'Spotify')], max_length=60, verbose_name='Podcasts Provider'),
        ),
    ]
