# Generated by Django 3.1.8 on 2021-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcasthomepage_podcastpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='podcast_id',
        ),
        migrations.RemoveField(
            model_name='podcastprovider',
            name='client_id',
        ),
        migrations.AddField(
            model_name='podcast',
            name='remote_id',
            field=models.CharField(default='', max_length=200, verbose_name='Provider ID of the podcast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcastprovider',
            name='api_key',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='podcastprovider',
            name='type',
            field=models.CharField(choices=[('sharpstream_v1', 'Sharpstream RSS API'), ('spotify', 'Spotify'), ('timbre', 'Timbre (Sharpstream)')], max_length=60, verbose_name='Podcasts Provider'),
        ),
    ]
