# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 23:40
from __future__ import unicode_literals

import api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(height_field='cover_height', upload_to=api.users.models.upload_to_profile_cover, width_field='cover_width'),
        ),
    ]
