# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 17:35
from __future__ import unicode_literals

import api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170523_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', upload_to=api.users.models.upload_to_profile_cover, width_field='cover_width'),
        ),
    ]
