# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('producer', 'Producer'), ('host', 'Host'), ('guest', 'Guest'), ('performer', 'Performer'), ('writer', 'Writer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('name', models.CharField(max_length=5)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('name', models.CharField(help_text='Name of the show', max_length=80, verbose_name='Show Name')),
                ('slug', models.SlugField()),
                ('short_description', models.CharField(help_text='A tiny one-sentence tag line for the show', max_length=90, verbose_name='Short description')),
                ('long_description', models.TextField(help_text='A long description for your show', verbose_name='Long description')),
                ('cover', models.ImageField(height_field='cover_height', upload_to='', width_field='cover_width')),
                ('cover_width', models.IntegerField(blank=True, null=True)),
                ('cover_height', models.IntegerField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, height_field='banner_height', null=True, upload_to='', width_field='banner_width')),
                ('banner_width', models.IntegerField(blank=True, null=True)),
                ('banner_height', models.IntegerField(blank=True, null=True)),
                ('brand_color', models.CharField(help_text='Color hex for show branding', max_length=6, verbose_name='Branding color')),
                ('emoji_description', models.CharField(help_text='Describe the show in a single emoji', max_length=4, verbose_name='Emoji')),
                ('has_interaction', models.BooleanField(default=False, help_text='Enable interactive features in the player, such as highlighting the sms number ', verbose_name='Enable interaction')),
                ('social_facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('social_twitter_handle', models.CharField(blank=True, max_length=35, null=True, verbose_name='Twitter handle')),
                ('social_mixcloud_handle', models.CharField(blank=True, max_length=35, null=True, verbose_name='Mixcloud handle')),
                ('social_snapchat_handle', models.CharField(blank=True, max_length=35, null=True, verbose_name='Snapchat handle')),
                ('social_soundcloud_handle', models.CharField(blank=True, max_length=35, null=True, verbose_name='Soundcloud handle')),
                ('social_instagram_handle', models.CharField(blank=True, max_length=35, null=True, verbose_name='Instagram handle')),
                ('social_youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(blank=True, height_field='cover_height', null=True, upload_to='', width_field='cover_width')),
                ('cover_width', models.IntegerField(blank=True, null=True)),
                ('cover_height', models.IntegerField(blank=True, null=True)),
                ('show_notes', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('run_time', models.PositiveIntegerField()),
                ('audio_resource', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowsConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_air', models.BooleanField(default=False)),
                ('automation_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.Show')),
                ('current_slate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.ScheduleSlate')),
            ],
            options={
                'verbose_name': 'Shows Configuration',
            },
        ),
        migrations.CreateModel(
            name='ShowSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('broadcast', 'Broadcast')], default='broadcast', max_length=20)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='shows.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shows.Show')),
                ('slate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='shows.ScheduleSlate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
