# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 23:40
from __future__ import unicode_literals

import api.shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170523_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodecredit',
            options={'verbose_name': 'Episode Credit'},
        ),
        migrations.AlterModelOptions(
            name='scheduleslate',
            options={'verbose_name': 'slate'},
        ),
        migrations.AlterModelOptions(
            name='showcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='showepisode',
            options={'verbose_name': 'episode', 'verbose_name_plural': 'episodes'},
        ),
        migrations.AlterModelOptions(
            name='showsconfiguration',
            options={'verbose_name': 'Shows Settings'},
        ),
        migrations.AlterModelOptions(
            name='showseries',
            options={'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterModelOptions(
            name='showslot',
            options={'verbose_name': 'slot'},
        ),
        migrations.AlterField(
            model_name='show',
            name='banner',
            field=models.ImageField(blank=True, height_field='banner_height', null=True, upload_to=api.shows.models.upload_to_show_banner, width_field='banner_width'),
        ),
        migrations.AlterField(
            model_name='show',
            name='cover',
            field=models.ImageField(height_field='cover_height', upload_to=api.shows.models.upload_to_show_cover, width_field='cover_width'),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='audio_resource',
            field=models.FileField(upload_to=api.shows.models.upload_to_episode_audio),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to=api.shows.models.upload_to_episode_cover, width_field='cover_width'),
        ),
    ]
