# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 08:20
from __future__ import unicode_literals

import api.shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20170523_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to=api.shows.models.upload_to_show_cover, width_field='cover_width'),
        ),
    ]
