# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20171002_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcategory',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Color hex for category', max_length=6, verbose_name='Branding color'),
        ),
    ]
