# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_showcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows.ShowCategory'),
        ),
    ]
