# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20171102_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
