# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-06 17:36
from __future__ import unicode_literals

import api.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_scheduleslate_automation_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='brand_color',
            field=models.CharField(help_text='Color hex for show branding', max_length=6, validators=[api.core.utils.validate_hex], verbose_name='Branding color'),
        ),
    ]
