# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-02 19:53
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200106_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
