# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    ShowSlot = apps.get_model('shows', 'ShowSlot')
    alias = schema_editor.connection.alias

    for slot in ShowSlot.objects.using(alias):
        slot.child_shows.add(slot.show)
        slot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_show_autoslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='showslot',
            name='child_shows',
            field=models.ManyToManyField(blank=True, related_name='connected_slots', to='shows.Show'),
        ),
        migrations.RunPython(forwards_func),
    ]
