# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_show_autoslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='showslot',
            name='week',
            field=models.IntegerField(blank=True, choices=[(1, 'Odd Weeks'), (2, 'Even Weeks')], default=None, null=True),
        ),
    ]
