# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-23 19:58
from __future__ import unicode_literals

import api.shows.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_showslot_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslate',
            name='broadcast_start_date',
            field=models.DateField(default=datetime.date(2020, 7, 6), validators=[api.shows.models.validate_monday], verbose_name='Broadcasting Start Date'),
            preserve_default=False,
        ),
    ]
