# Generated by Django 3.1.8 on 2021-06-05 23:58

import api.shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20200731_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=api.shows.models.upload_to_show_banner),
        ),
        migrations.AlterField(
            model_name='show',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.shows.models.upload_to_show_cover),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.shows.models.upload_to_episode_cover),
        ),
    ]
