# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('host', models.CharField(max_length=80)),
                ('port', models.IntegerField()),
                ('mountpoint', models.CharField(default='/stream', max_length=40)),
                ('priority_online', models.IntegerField(default=10, verbose_name='Online Priority')),
                ('priority_offline', models.IntegerField(default=3, verbose_name='Offline Priority')),
                ('metadata_source', models.CharField(choices=[('slate', 'Active Slate'), ('icecast', 'Icecast')], max_length=30)),
            ],
            options={
                'verbose_name': 'Stream',
            },
        ),
    ]
