# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20171119_1722'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamconfiguration',
            name='slate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.ScheduleSlate', verbose_name='Active Slate'),
        ),
        migrations.AddField(
            model_name='streamconfiguration',
            name='slug',
            field=models.SlugField(default='urf-online', unique=True),
            preserve_default=False,
        ),
    ]
