# Generated by Django 3.0.8 on 2020-07-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20200731_1517'),
        ('streams', '0002_add_proxy_and_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamconfiguration',
            name='slate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.ScheduleSlate', verbose_name='Active Slate'),
        ),
    ]
