# Generated by Django 3.1.8 on 2021-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20200731_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamconfiguration',
            name='host',
        ),
        migrations.RemoveField(
            model_name='streamconfiguration',
            name='mobile_mountpoint',
        ),
        migrations.RemoveField(
            model_name='streamconfiguration',
            name='mountpoint',
        ),
        migrations.RemoveField(
            model_name='streamconfiguration',
            name='port',
        ),
        migrations.AddField(
            model_name='streamconfiguration',
            name='status_url',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Status URL'),
        ),
        migrations.AddField(
            model_name='streamconfiguration',
            name='type',
            field=models.CharField(choices=[('ICECAST', 'Icecast'), ('SHARPSTREAM', 'SharpStream')], default='ICECAST', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamconfiguration',
            name='proxy_url',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Stream URL'),
        ),
    ]
