# Generated by Django 3.1.13 on 2021-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_sharpstream_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamconfiguration',
            name='api_key',
            field=models.CharField(blank=True, default=None, help_text='API key for status queries for providers that require it.', max_length=4096, null=True, verbose_name='API key'),
        ),
    ]
