# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 15:51
from __future__ import unicode_literals

import api.articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0003_auto_20170523_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('featured_image', models.ImageField(blank=True, height_field='cover_height', null=True, upload_to=api.articles.models.upload_to_article_featured, width_field='cover_width')),
                ('featured_image_width', models.IntegerField(blank=True, null=True)),
                ('featured_image_height', models.IntegerField(blank=True, null=True)),
                ('tone', models.CharField(choices=[('INTERVIEW', 'Interview'), ('PREVIEW', 'Preview'), ('REVIEW', 'Review'), ('OPINION', 'Opinion'), ('ANNOUNCEMENT', 'Announcement'), ('BLOG', 'Blog')], default='BLOG', max_length=20)),
                ('content', models.CharField(max_length=2, default='')),
                ('associated_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shows.Show')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
