# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20171102_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
    ]
