# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171105_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
