# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('short_description', models.TextField()),
                ('location', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('facebook_event', models.URLField(blank=True, null=True, verbose_name='Facebook Event URL')),
                ('ussu_event', models.URLField(blank=True, null=True, verbose_name='Students Union Event Page URL')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.UrfImage')),
            ],
        ),
    ]
