# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20171102_1315'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='associated_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_event',
            field=models.URLField(blank=True, default='', verbose_name='Facebook Event URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ussu_event',
            field=models.URLField(blank=True, default='', verbose_name='Students Union Event Page URL'),
        ),
    ]
