# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageblock',
            old_name='publish_at',
            new_name='published_at',
        ),
    ]
