# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171105_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageblock',
            name='override_background_color',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='override_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='override_kicker',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='override_title',
            field=models.CharField(default='', max_length=265),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='position',
            field=models.CharField(choices=[('HERO', 'Hero'), ('SEC_1', 'Secondary 1'), ('SEC_2', 'Secondary 2'), ('THIRD_1', 'Third 1'), ('THIRD_2', 'Third 2'), ('THIRD_3', 'Third 3')], max_length=12),
        ),
    ]
