# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171119_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='override_background_color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='override_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='override_kicker',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='override_title',
            field=models.CharField(blank=True, default='', max_length=265),
        ),
    ]
