# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171122_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='position',
            field=models.CharField(choices=[('HERO', 'Hero'), ('SEC_1', 'Secondary 1'), ('SEC_2', 'Secondary 2'), ('THIRD_1', 'Third 1'), ('THIRD_2', 'Third 2'), ('THIRD_3', 'Third 3'), ('FOURTH_1', 'Fourth 1'), ('FOURTH_2', 'Fourth 2'), ('FOURTH_3', 'Fourth 3'), ('FOURTH_4', 'Fourth 4')], max_length=12),
        ),
    ]
