# Generated by Django 3.0.8 on 2020-07-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0005_auto_20190304_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'shows'), ('model', 'show')), models.Q(('app_label', 'articles'), ('model', 'article')), models.Q(('app_label', 'events'), ('model', 'event')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
